//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with specified email address already exist.
        /// </summary>
        internal static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        internal static string JwtInvalidToken {
            get {
                return ResourceManager.GetString("JwtInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This token hasn&apos;t expired yet.
        /// </summary>
        internal static string JwtNotExpired {
            get {
                return ResourceManager.GetString("JwtNotExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This refresh token has expired.
        /// </summary>
        internal static string JwtRefreshExpired {
            get {
                return ResourceManager.GetString("JwtRefreshExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This refresh token has been invalidated.
        /// </summary>
        internal static string JwtRefreshInvalidated {
            get {
                return ResourceManager.GetString("JwtRefreshInvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This refresh token does not exist.
        /// </summary>
        internal static string JwtRefreshNotExist {
            get {
                return ResourceManager.GetString("JwtRefreshNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This refresh token does not match this JWT.
        /// </summary>
        internal static string JwtRefreshNotMatchJwt {
            get {
                return ResourceManager.GetString("JwtRefreshNotMatchJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This refresh token has been used.
        /// </summary>
        internal static string JwtRefreshUsed {
            get {
                return ResourceManager.GetString("JwtRefreshUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &quot;{0}&quot; with id (&quot;{1}&quot;) was not found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not own this post..
        /// </summary>
        internal static string Post_UserDoNotOwnPost {
            get {
                return ResourceManager.GetString("Post_UserDoNotOwnPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation failures have occurred..
        /// </summary>
        internal static string ValidationFailure {
            get {
                return ResourceManager.GetString("ValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/password combination is wrong.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
